# Generated by Django 5.2.4 on 2026-02-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='cpd',
            new_name='cpf',
        ),
    ]
